  - name: Make sure pymysql is present
    become: true # needed if the other tasks are not played as root
    pip:
     name:
       - "flask-mysql"
       - "flask"
     state: present

  - name: Create mysql DB
    mysql_db:
      name: employee_db
      state: present

  - name: Create DB user
    mysql_user:
      name: db_user
      password: Passw0rd
      priv: '*.*:ALL'
      state: present
      host: '%'


  - name: Copy source code
    copy:
      src: app.py
      dest: /opt/app.py


  - name: permit traffic 5000
    firewalld:
     zone: public
     port: 5000/tcp
     permanent: true
     state: enabled
     immediate: yes

  - name: reload service firewalld
    systemd:
     name: firewalld
     state: reloaded


  - name: Start web server
    shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
