- name: Install MySQL community repository
  yum:
     name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
     disable_gpg_check: yes
     state: present

- name: Install mysql
  yum:
    state: present
    name:
     - "mysql-server"
     - "mysql-devel"

- name: Start mysql
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Start mysql
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Create mysql DB
  mysql_db:
    name: employee_db
    state: present

- name: Create DB user
  mysql_user:
    name: db_user
    password: Passw0rd
    priv: '*.*:ALL'
    state: present
    host: '%'
